apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-python
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: python-manifest
    repoURL: https://github.com/jain-aayush1123/devops-python
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
