apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-python
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    chart: hello-python
    repoURL: https://github.com/jain-aayush1123/argocd-app-config
    targetRevision: 1.0.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
