apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-python
  name: hello-python
  namespace: { { .Values.namespace.name } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: hello-python
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          name: hello-python
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
